### ISSUE TITLE
Which NDK version is compatible to build this project?

### ISSUE THREAD

**Issue by ganny26** [alexbirkett/QuietShare#3]
Hello @alexbirkett ,

I'm tried building app with NDK android-ndk-r15c-windows-x86_64 but getting below 3 errors.

Error:error: typedef redefinition with different types ('__kernel_fd_set' vs 'struct fd_set')
Error:error: typedef redefinition with different types ('u32_t' (aka 'unsigned int') vs '__socklen_t' (aka 'int'))
Error:Execution failed for task ':quiet:ndkBuild'.
> Process 'command 'C:\Users\Downloads\android-ndk-r15c-windows-x86_64\android-ndk-r15c/ndk-build.cmd'' finished with non-zero exit value 2

Which is the best suitable NDK need to use for building APK.

**Comment by brian-armstrong** [comment]
Hi @ganny26

This is most likely related to https://github.com/quiet/org.quietmodem.Quiet/issues/11

**Comment by brian-armstrong** [comment]
Hi @ganny26 

The bug in https://github.com/quiet/org.quietmodem.Quiet/issues/11 has possibly been fixed by v0.1.1, can you check if that fixes it for you?

**Comment by ganny26** [comment]
@brian-armstrong Yeah it is working fine now

**Comment by nejc-skerjanc** [comment]
I still have same problems as is described above. I am not sure if problem is fixed in version 0.1.1. For this app and  in library I use NDK 25. 

Do i need anything additional to do before compile?

**Comment by brian-armstrong** [comment]
It looks like v0.1.2 is what you want to be on, not 0.1.1. https://github.com/quiet/org.quietmodem.Quiet/releases/tag/v0.1.2
